{% set version = '0.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-webshot2
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/webshot2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/webshot2/webshot2_{{ version }}.tar.gz
  sha256: bc76716c209e9fbca5986f65e0bdecbb1a75463bb6ae95938b3c40e2278dc58b

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-callr
    - r-chromote >=0.1.0
    - r-later
    - r-magrittr
    - r-promises
  run:
    - r-base
    - r-callr
    - r-chromote >=0.1.0
    - r-later
    - r-magrittr
    - r-promises

test:
  commands:
    - $R -e "library('webshot2')"           # [not win]
    - "\"%R%\" -e \"library('webshot2')\""  # [win]

about:
  home: https://github.com/rstudio/webshot2
  license: GPL-2.0-only
  summary: Takes screenshots of web pages, including Shiny applications and R Markdown documents.
    'webshot2' uses headless Chrome or Chromium as the browser back-end.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - jdblischak

# Package: webshot2
# Title: Take Screenshots of Web Pages
# Version: 0.1.0
# Authors@R: c( person("Winston", "Chang", role = c("aut", "cre"), email = "winston@rstudio.com"), person("Barret", "Schloerke", role = c("ctb"), email = "barret@rstudio.com", comment = c(ORCID = "0000-0001-9986-114X")), person(given = "RStudio", role = c("cph", "fnd")) )
# Description: Takes screenshots of web pages, including Shiny applications and R Markdown documents. 'webshot2' uses headless Chrome or Chromium as the browser back-end.
# Imports: chromote (>= 0.1.0), later, promises, magrittr, callr
# Suggests: shiny, httpuv, rmarkdown
# Depends: R (>= 3.2)
# License: GPL-2
# Encoding: UTF-8
# RoxygenNote: 7.2.0
# URL: https://github.com/rstudio/webshot2
# BugReports: https://github.com/rstudio/webshot2/issues
# Language: en-US
# NeedsCompilation: no
# Packaged: 2022-05-13 19:54:06 UTC; barret
# Author: Winston Chang [aut, cre], Barret Schloerke [ctb] (<https://orcid.org/0000-0001-9986-114X>), RStudio [cph, fnd]
# Maintainer: Winston Chang <winston@rstudio.com>
# Repository: CRAN
# Date/Publication: 2022-05-18 06:00:02 UTC
