{% set version = "0.1.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-webshot2
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/webshot2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/webshot2/webshot2_{{ version }}.tar.gz
  sha256: 27aa449ef9174c0563c5905800bc85eb1106c3470a3075e3d8040e4eda782e94

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-callr
    - r-chromote >=0.1.0
    - r-later
    - r-magrittr
    - r-promises
  run:
    - r-base
    - r-callr
    - r-chromote >=0.1.0
    - r-later
    - r-magrittr
    - r-promises

test:
  commands:
    - $R -e "library('webshot2')"           # [not win]
    - "\"%R%\" -e \"library('webshot2')\""  # [win]

about:
  home: https://github.com/rstudio/webshot2
  license: MIT
  summary: Takes screenshots of web pages, including Shiny applications and R Markdown documents. 'webshot2' uses headless Chrome or Chromium as the browser back-end.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - jdblischak
